#!/usr/bin/env python3
"""Generate the Windows version resource consumed by PyInstaller.

Windows shows this information in the file properties of the EXE and in the installer's Add/Remove
Programs entry, so it must match ``src/dentivapro/version.py`` exactly. Run before ``pyinstaller``::

    python packaging/make_version_info.py            # writes packaging/version_info.txt
    python packaging/make_version_info.py --check    # fails when the file is out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from dentivapro.version import (  # noqa: E402
    APP_EXECUTABLE,
    APP_ID,
    APP_NAME,
    APP_SLUG,
    CREATOR_EMAIL,
    CREATOR_NAME,
    PRODUCT_DESCRIPTION,
    __version__,
    version_tuple,
)

TARGET = Path(__file__).resolve().parent / "version_info.txt"

TEMPLATE = """# UTF-8 - generated by packaging/make_version_info.py, do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringStruct('CompanyName', {publisher}),
            StringStruct('FileDescription', {description}),
            StringStruct('FileVersion', {version}),
            StringStruct('InternalName', {slug}),
            StringStruct('LegalCopyright', {copyright}),
            StringStruct('OriginalFilename', {executable}),
            StringStruct('ProductName', {product}),
            StringStruct('ProductVersion', {version}),
          ],
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def render() -> str:
    return TEMPLATE.format(
        # PyInstaller's version resource wants a 4-tuple; the build field is always zero here.
        version_tuple="(" + ", ".join(f"{part}" for part in (*version_tuple(), 0)) + ")",
        publisher=repr(CREATOR_NAME),
        description=repr(PRODUCT_DESCRIPTION),
        version=repr(__version__),
        slug=repr(APP_SLUG),
        copyright=repr(f"Copyright (c) {CREATOR_NAME} <{CREATOR_EMAIL}>"),
        executable=repr(APP_EXECUTABLE),
        product=repr(APP_NAME),
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the file would change")
    args = parser.parse_args(argv)

    content = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != content:
            print(f"{TARGET.name} is out of date; run: python packaging/make_version_info.py")
            return 1
        print(f"{TARGET.name} is up to date ({APP_NAME} {__version__}, {APP_ID})")
        return 0

    TARGET.write_text(content, encoding="utf-8")
    print(f"wrote {TARGET} for {APP_NAME} {__version__} ({APP_ID})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
